Repository story-squad/classroom-rumble, pull requests merged in 2021-04, with the labels that each got.

#45 Feature/student teacher get feedback
  src/api/Feedback/feedback.ts
  src/api/Feedback/feedbackTypes.ts
  src/api/Feedback/index.ts
  src/api/Students/students.ts
  src/api/index.ts
  src/assets/img/Alien.svg
  src/components/common/CouldNotLoad/CouldNotLoad.tsx
  src/components/common/Feedback/FeedbackContainer.tsx
  src/components/common/Feedback/RenderFeedback.tsx
  src/components/common/Feedback/feedbackTypes.ts
  src/components/common/Feedback/index.ts
  src/components/common/FullscreenImage/FullscreenImage.tsx
  src/components/common/Header/Header.tsx
  src/components/common/Modal/Modal.tsx
  src/components/common/Submission/Submission.tsx
  src/components/common/Submission/index.ts
  src/components/common/index.ts
  src/components/pages/StudentDashboard/StudentViewRumble/StudentRumblePages/PastRumbleDetails/index.ts
  src/components/pages/StudentDashboard/StudentViewRumble/StudentRumblePages/ViewSubmission/RenderViewSubmission.tsx
  src/components/pages/StudentDashboard/StudentViewRumble/StudentRumblePages/ViewSubmission/ViewSubmissionContainer.tsx
  src/components/pages/StudentDashboard/StudentViewRumble/StudentRumblePages/ViewSubmission/index.ts
  src/components/pages/StudentDashboard/StudentViewRumble/StudentRumblePages/index.ts
  src/components/pages/StudentDashboard/StudentViewRumble/StudentRumbleRedirect.tsx
  src/components/pages/TeacherDashboard/TeacherViewSubmission/RenderTeacherViewSubmission.tsx
  src/hooks/index.ts
  src/hooks/useKeyPress/index.ts
  src/hooks/useKeyPress/useKeyPress.ts
  src/styles/components/common/couldNotLoad.scss
  src/styles/components/common/fullscreenImage.scss/fullscreenImage.scss
  src/styles/components/common/fullscreenImage.scss/imageControls.scss
  src/styles/components/common/fullscreenImage.scss/imageInfo.scss
  src/styles/components/common/fullscreenImage.scss/imageWrapper.scss
  src/styles/components/common/submission.scss
  src/styles/components/pages/teacherDashboard/teacherViewSubmission.scss
  src/styles/index.scss
Labels: enhancement

#47 Refactor/feedback styles
  src/components/common/Submission/Submission.tsx
  src/styles/components/common/feedback.scss
  src/styles/components/common/submission.scss
  src/styles/components/pages/teacherDashboard/teacherDashboard.scss
  src/styles/components/pages/teacherDashboard/teacherViewSubmission.scss
  src/styles/index.scss
Labels: Tweaks

#55 Bugfix/teacher dashboard current
  src/components/pages/TeacherDashboard/RenderTeacherDashboard.tsx
  src/components/pages/TeacherDashboard/TeacherDashboardRumbleList/TeacherDashboardRumbleList.tsx
Labels: Tweaks, bug

#60 Styling/cookie popup
  src/styles/components/common/cookiePopup.scss
  src/styles/index.scss
Labels: enhancement

#57 added props
  src/components/common/Submission/Submission.tsx
  src/components/pages/StudentDashboard/StudentViewRumble/StudentRumblePages/ViewSubmission/RenderViewSubmission.tsx
Labels: Tweaks, enhancement

#56 Bugfix/no rumbles tweak
  src/assets/img/empty_inbox.svg
  src/assets/img/no_rumbles.svg
  src/components/common/Header/Menu/Logout.tsx
  src/components/pages/StudentDashboard/StudentViewSection/RenderStudentViewSection.tsx
  src/components/pages/TeacherDashboard/TeacherDashboardRumbleList/TeacherDashboardRumbleList.tsx
  src/styles/components/common/header.scss
  src/styles/components/common/menu.scss
  src/styles/components/pages/studentDashboard/studentViewRumblePage/studentClassList.scss
  src/styles/components/pages/teacherDashboard/teacherDashboardRumbleList.scss
  src/styles/index.scss
  src/styles/mediaQueries.scss
Labels: Tweaks, bug, enhancement

#59 Adds isTeacher prop to PromptBox.
  src/components/pages/TeacherDashboard/TeacherViewSubmission/RenderTeacherViewSubmission.tsx
Labels: bug

#58 Bugfix/student sees start feedback button
  src/components/common/PromptBox/PromptBoxContainer.tsx
  src/components/common/PromptBox/RenderPromptBox.tsx
Labels: bug

#61 Styling/peer feedback form
  src/components/common/RadioGroup/RadioGroup.tsx
  src/components/pages/StudentDashboard/StudentViewRumble/StudentRumblePages/PeerFeedbackPage/FeedbackForm.tsx
  src/components/pages/StudentDashboard/StudentViewRumble/StudentRumblePages/PeerFeedbackPage/FeedbackSubmissionCard.tsx
  src/components/pages/StudentDashboard/StudentViewRumble/StudentRumblePages/PeerFeedbackPage/RenderPeerFeedback.tsx
  src/styles/components/common/feedbackForm.scss
  src/styles/components/common/promptBox.scss
  src/styles/components/common/submission.scss
  src/styles/index.scss
Labels: enhancement
